export const data = {
  employees: [
    {
      name: "Alice Johnson",
      email: "alice@example.com",
      role: "Administrator",
      active: true,
      status: "Active",
      designation: "System Administrator",
      dateOfBirth: "1990-01-15",
    },
    {
      name: "Bob Smith",
      email: "bob@example.com",
      role: "Developer",
      active: true,
      status: "Active",
      designation: "Software Developer",
      dateOfBirth: "1985-07-20",
    },
    {
      name: "Charlie Brown",
      email: "charlie@example.com",
      role: "Manager",
      active: false,
      status: "Inactive",
      designation: "Project Manager",
      dateOfBirth: "1978-11-10",
    },
    {
      name: "David Lee",
      email: "david@example.com",
      role: "Engineer",
      active: true,
      status: "Active",
      designation: "Senior Engineer",
      dateOfBirth: "1992-03-25",
    },
    {
      name: "Emma Taylor",
      email: "emma@example.com",
      role: "Administrator",
      active: true,
      status: "Active",
      designation: "Network Administrator",
      dateOfBirth: "1983-09-05",
    },
    {
      name: "Frank Rodriguez",
      email: "frank@example.com",
      role: "Developer",
      active: true,
      status: "Active",
      designation: "Frontend Developer",
      dateOfBirth: "1987-06-12",
    },
    {
      name: "Grace Martinez",
      email: "grace@example.com",
      role: "Engineer",
      active: false,
      status: "Inactive",
      designation: "Backend Engineer",
      dateOfBirth: "1980-04-30",
    },
    {
      name: "Henry Wong",
      email: "henry@example.com",
      role: "Manager",
      active: true,
      status: "Active",
      designation: "IT Manager",
      dateOfBirth: "1975-12-18",
    },
    {
      name: "Ivy Clark",
      email: "ivy@example.com",
      role: "Developer",
      active: true,
      status: "Active",
      designation: "Full Stack Developer",
      dateOfBirth: "1994-02-08",
    },
    {
      name: "Jack White",
      email: "jack@example.com",
      role: "Engineer",
      active: true,
      status: "Active",
      designation: "Software Engineer",
      dateOfBirth: "1989-10-22",
    },
  ],
};
